print("≈≈≈≈≈≈≈≈≈≈≈≈≈")
print()
print(" →   我的腰： ）.（")
print(" →   你的腰：（ . ）")
print(" →   我的钱： ∞")
print(" →   你的钱： 8")
print(" →   我的眼： ⊙_⊙")
print(" →   你的眼： • _ •")
print()
print("≈≈≈≈≈≈≈≈≈≈≈≈≈")
