print("       ┌─────┐")
print("       │ 照高星吉 │")
print("       └─────┘")
print("  ┌─┐              ┌─┐")
print("  │万│              │一│")
print("  │事│              │帆│")
print("  │如│              │风│")
print("  │意│              │顺│")
print("  │步│              │年│")
print("  │步│              │年│")
print("  │高│              │好│")
print("  └─┘              └─┘")
