print(' '*16,'轻松背单词  V2.0')
print('='*50)
print('-'*50)
print(' '*16,'1.单词背诵')
print(' '*16,'2.发音合成')
print(' '*16,'3.课本同步')
print(' '*16,'4.成绩排行')
print(' '*16,'5.退出程序')
print('='*50)
print('力线工作室   http://lianxian.net.cn')
print('请使用↑↓或相应数字键选择菜单项，回车执行！！')
