print("NNNNN             BBBBBBBBBBB")
print("NNNNN            BBBBBBBBBBBBB")
print("NNNNN           BBBBB")
print("                BBBB")
print("NNNNN          BBBB   BBBBBBBB")
print("NNNNN         BBBB   BBBBBBBBBB")
print("NNNNN         BBBB   BBB    BBBB")
print("NNNNN         BBBB   BBB    BBBB")
print("NNNNN         BBBB           BBBB")
print("NNNNN          BBBBB         BBBB")
print("NNNNN           BBBBBBBBBBBBBBBB")
print("NNNNN            BBBBBBBBBBBBB")
