print("       ")
print("  <微信支付                   @   ")
print("                                  ")
print("  微信支付凭证                    ")
print("                付款金额          ")
print("                ￥ 10000.00       ")
print("  收款方   孙铁新     ")
print("  交易状态支付成功，对方已收款    ")
print("—————————————————")
print("  查看账单详情                    ")
